name: 'coverage-report'
on:
  push:
    branches:
      - main

concurrency:
  group: coverage-report-${{ github.ref }}
  cancel-in-progress: false

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: 8.4
          coverage: none
          tools: composer:v2
          extensions: xdebug
      - name: Install Dependencies
        run: composer install -q --profile --ignore-platform-reqs --no-interaction --no-ansi --no-scripts --prefer-dist
      - name: "Create Empty env File for Docker"
        run: touch .env
      - name: PHPUnit
        run: docker compose run --user "$(id -u):$(id -g)" phpunit
      - name: "Parse Coverage"
        run: "php ./generate_coverage_report.php"
      - name: Create Coverage Badges
        uses: jaywcjlove/coverage-badges-cli@998665f7962b1a3935ba8c3e786171a99436e5d1 # v2.3.0
        with:
          source: cov/json/index.json
          output: cov/html/coverage.svg
          jsonPath: total.statements.pct
      - name: Upload GitHub Pages artifact 📦
        uses: actions/upload-pages-artifact@v5
        with:
          path: cov/html

  deploy-pages:
    name: Deploy to GitHub Pages 🚀
    needs: coverage-report
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5