name: 'coverage-diff'
on:
  pull_request:
    branches:
      - master
      - main
      - chore/code-coverage # remove this after merged to main
  push: # remove before merge to main
    branches:
      - chore/code-coverage
jobs:
  coverage-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer:v2
          extensions: xdebug
      - name: Install Dependencies
        run: composer install -q --profile --ignore-platform-reqs --no-interaction --no-ansi --no-scripts --no-suggest --prefer-dist
      - uses: KengoTODA/actions-setup-docker-compose@4677f0d86d41e623c9c6e11e1d910976da297bc0
        with:
          version: '2.14.2'
      - name: Set Permissions for Coverage Directory
        run: |
          mkdir -p cov/json cov/xml cov/html
          chmod -R 777 cov
      - name: "Create Empty env File for Docker"
        run: touch .env
      - name: PHPUnit
        run: docker-compose run phpunit --coverage-xml cov/xml --coverage-html cov/html --coverage-clover=cov/xml/clover.xml
      - name: Get Cover
        uses: orgoro/coverage@3f13a558c5af7376496aa4848bf0224aead366ac
        with:
          coverageFile: ./cov/xml/clover.xml
          token: ${{ secrets.GITHUB_TOKEN }}