name: Functional tests

on:
  pull_request_target:
    branches:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  functional_tests:
    name: "Functional Tests PHP ${{ matrix.php_version }}"
    runs-on: "ubuntu-latest"

    strategy:
      max-parallel: 1
      matrix:
        php_version: [ "8.1", "8.2", "8.3", "8.4" ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup PHP
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231
        with:
          php-version: "${{ matrix.php_version }}"
          coverage: none
          tools: composer:v2
      - name: Install Dependencies
        run: composer install -q --profile --ignore-platform-reqs --no-interaction --no-ansi --no-scripts --no-suggest --prefer-dist
      - name: "Try to get data using SDK"
        run: "php ./run_checks.php"
        env:
          FP_PRIVATE_API_KEY: "${{ secrets.FP_PRIVATE_API_KEY }}"
          FP_API_HOST: "${{ secrets.FP_API_HOST }}"

  report-status:
    needs: functional_tests
    if: always()
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/report-workflow-status.yml@v1
    with:
      notification_title: 'PHP SDK Tests has {status_message}'
      job_status: ${{ needs.functional_tests.result }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
